{% set name = "xmltodict" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmltodict-{{ version }}.tar.gz
  sha256: 341595a488e3e01a85a9d8911d8912fd922ede5fecc4dce437eb4b6c8d037e56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - xmltodict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martinblech/xmltodict
  license: MIT
  license_file: LICENSE
  summary: Makes working with XML feel like you are working with JSON
  dev_url: https://github.com/martinblech/xmltodict

extra:
  recipe-maintainers:
    - synapticarbors
    - ocefpaf
