{% set name = "xmltodict" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmltodict-{{ version }}.tar.gz
  sha256: 338c8431e4fc554517651972d62f06958718f6262b04316917008e8fd677a6b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - xmltodict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martinblech/xmltodict
  license: MIT
  license_file: LICENSE
  summary: Makes working with XML feel like you are working with JSON
  dev_url: https://github.com/martinblech/xmltodict

extra:
  recipe-maintainers:
    - synapticarbors
    - ocefpaf
