travis:
  secure:
    BINSTAR_TOKEN: jn7mMz3gA698jGEHbV9Qte2VD4MtomMaDiE0I83r4KvXTJvgYaCRIV7Y0431f9hMma3/qRGrJDChPv0qsv0zNpNiVcYmY8Ndl2LOJ3x6S8caR7z/fykvGM22ZUTVpp7AeKVwvzT5+VKdj4piITEowA8QV97or6FwYhN/sjFugvoTXjpDmI1779sthvZ2bOeJ0Q05RLtqCQOH2vRnPuC5FlDBTCTpJ+Ym3nOmmaZ2DWh8P4cGkIZvvtIudRc1pOxCaZ8FSU2RVPERtHXttT9PWUhx8rJ9FXD1rX4uH8NvzAhh5Fi5NOGTrSnTSkED1lpD9Rr72e3qYitZpv5pX4zhQhN4UnwiowVXGcp02rnfCuieGmUBCgzBMxzaaR/QxngHik5c01RzcdbRod5Ceovkoprvt2QyTqnKMusGdkNsSothipDziROQN06q8Ty8jYVour8JCrzYf45XH6NZKn2IYdubK/IbjKaluAhdNkv78+o8OCTkJt+ZbqLc6udNsjaKyAfCB9dbu8SInVbCDxgHk08etjlSKbHK8R+xLEvCG+wOG75UBprGBLLNBKXS4CJhY+4IFa7KLxRgzzW2PmhTHqBySsY23j+XaeFr75x8ueBoSW1QIxLV0bhHT8++O5CWiG+CooJYcp04bMD/ZW89E+RL9HOpR7bB7tqQdtWmGR8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
