travis:
  secure:
    BINSTAR_TOKEN: jXgrrLwEE7K8L1XxUHFAfWIbVO8++xrl+j604MB+EEEmhyGwG9l3mfnuT7FNR71cp0NIvyhtTiydWorR9rpZlskEXvIN2ldy+t2Kf3ol96IK/KG8shmjkA8cEiIKRtupamTVob9fpQ4aAHLUmgFiCC4FuyiMjbIssMn6YSGuw84hiT0i1/SVLoOKPxL7/baJpbqiAs19j1a402ytArnwo6Q5MtsHlX9OPsaXI27ibza2NPlo4/zCY56y/uG3S1D+ymP2u0c7yldB2bplIzGYv6AYOGA1Q+2gAqaJOFlEAQR39iVpwo2K8iyMbeT0nfaEafRjufm1Sp9PpmUtH4N0pun6Gn4d5ds54WUWzUoUeWRg70z1sfFAm+TFaLsdXtkjyy5maZZiQMs8kR0cZWYE8+xsJ/SUH8qekW5+ZpWpNzJN+nPN7oMX/7RGpVTqqXGuZijG60J9mApxtQwasnoJ2MARZSj6dpZCjQmv3YYDMTXO6DyJGlcGgWwUft4wDx8jPUAc6jJ4jmAy7elXjD27qqXnG3/MuIkVx7dhC1xgO19gaCSqINrWip1acCtkvGf4g4Hcn133MwHPKYEsh6pvCBxXfFEp3afIFSQnZSYt2sJ/AfgDEXV5+0OwLrF7vAnRD3+KmJMlL4fzkAvzDYj9iCv/WauManRTkUFHKzSD/nc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
